name: egresadoapp
description: Trabajo de fin de grado de Ricardo Mejías Travieso, DAM - IES Saladillo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  email_validator: ^2.0.1
  google_fonts: ^4.0.4
  fluro: ^2.0.3
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.12
  flutter_svg: ^2.0.6
  flutter_dialogs: ^3.0.0
  flutter_spinkit: ^5.1.0
  overlay_support: ^2.1.0
  flutter_staggered_animations: ^1.0.0
  url_strategy: ^0.2.0
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  multi_select_flutter: ^4.1.2
  image_picker: ^0.8.5+3
  flutter_markdown: ^0.6.10
  url_launcher: ^6.1.3
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo512.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
  image_picker_android: 0.8.4+13
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/markdown_files/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
