// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU93UJdiWmul8utZHdxcvgOQY0uDDBRnU',
    appId: '1:673256565508:web:4c079e89aa7e6ad248be51',
    messagingSenderId: '673256565508',
    projectId: 'egresadoapp',
    authDomain: 'egresadoapp.firebaseapp.com',
    storageBucket: 'egresadoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35AudAaDESwO1tYAj5WxKNvgxEmkL2Cg',
    appId: '1:673256565508:android:7953a9e8b2eea6a548be51',
    messagingSenderId: '673256565508',
    projectId: 'egresadoapp',
    storageBucket: 'egresadoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7prWtguP0w2X5bimhzSvFuKYVxtQ89E',
    appId: '1:673256565508:ios:8089cb161b4d01dd48be51',
    messagingSenderId: '673256565508',
    projectId: 'egresadoapp',
    storageBucket: 'egresadoapp.appspot.com',
    iosClientId: '673256565508-5e0ahu5rbr3s5vo6v1ns7ogo1bqfnr9n.apps.googleusercontent.com',
    iosBundleId: 'com.saladillo.egresadoapp',
  );
}
